# Main language
language: cpp

# Environment
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - swig3.0
      - doxygen
      - libssh-dev
      - g++-7
      - libpoco-dev

before_install:
  - cd test/docker
  - docker-compose up --build -d
  - cd ../..

sudo: required

services:
  - docker

# Configuration
branches:
  only:
   - master
   - develop
   - /^release\/.*/

# Build steps
script:
  - mkdir -p build
  - cd build
  - cmake --version
  - CC=gcc-7 CXX=g++-7 cmake ..
  - make -k experimaestro-tests && test/experimaestro-tests
