site_name: experimaestro
site_description: experimaestro Computer science experiments manager and scheduler

pages:

- Basics: 
    - Basics: 'index.md'
    - Main concepts: 'main concepts.md'
    - Installing: 'installing.md'

- Scheduler:
    - Home: scheduler/index.md
    - "Connectors & Launchers": scheduler/connectors.md
    - Notification: scheduler/notification.md
- Manager:
    - Intro: manager/intro.md
    - Definitions: manager/definitions.md
    - Output: manager/json.md
    - Java: manager/java.md
    - Python: manager/python.md

- Developing: developing.md

theme: 
    name: material
    feature:
        tabs: true
    palette:
        primary: 'indigo'
        accent: 'indigo'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'

markdown_extensions:
  # https://pypi.org/project/markdown-include
  - markdown_include.include:
       base_path: .
  - codehilite
  - admonition
  - pymdownx.superfences

extra_javascript:
    - xpm.js

extra_css:
    - xpm.css

repo_url: 'https://github.com/bpiwowar/experimaestro'