version: 2

jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Installing packages
          command: |
            apt-get update
            apt-get install -y libpoco-dev git g++ cmake libssh-dev swig ninja-build doxygen python3-dev pkg-config
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
      - run:
          name: Creating Build Files
          command: |
            cmake -GNinja -H. -Bbuild
      - run:
          name: Building
          command: |
            ninja -j 2 -C build experimaestro-tests
      - run:
          name: Test
          # TODO: run SSH server to test remote calls
          command: |
            GTEST_FILTER="-SshTest.*" CTEST_OUTPUT_ON_FAILURE=1 ninja -C build test